language: go
go:
  - "1.x"

addons:
  apt:
    packages:
    - xz-utils

sudo: required
services:
  - docker

env:
  - GOVERSION=1.13

before_install:
  - chmod +x ./run_tests.sh

install: true

cache:
  directories:
    - ~/.cache

script:
  - ./run_tests.sh
